export const GET_PLANETS = 'GET_PLANETS';

export const GET_NEXT_PLANETS_INFO = 'GET_NEXT_PLANETS_INFO';

export const GET_NEXT_PLANETS_INFO_SUCCESS = 'GET_NEXT_PLANETS_INFO_SUCCESS';

export const GET_PLANETS_SUCCESS = 'GET_PLANETS_SUCCESS';

export const SET_PLANETS_PAGEINFO = 'SET_PLANETS_PAGEINFO';
